// Mock data for development and demonstration

import type { Alumni, Campaign, EngagementMetric } from "./types"

export const mockAlumni: Alumni[] = [
  {
    id: "alum-001",
    name: "Sarah Chen",
    email: "sarah.chen@tech.com",
    graduationYear: 2015,
    major: "Computer Science",
    lastDonation: 5000,
    totalDonations: 15000,
    engagementScore: 92,
    lastEngagementDate: "2025-10-15",
    interests: ["Technology", "Education", "Mentorship"],
    location: "San Francisco, CA",
    jobTitle: "VP Engineering",
    company: "TechCorp",
  },
  {
    id: "alum-002",
    name: "Michael Rodriguez",
    email: "mrodriguez@finance.com",
    graduationYear: 2012,
    major: "Business Administration",
    lastDonation: 2500,
    totalDonations: 8500,
    engagementScore: 78,
    lastEngagementDate: "2025-09-20",
    interests: ["Business", "Entrepreneurship", "Scholarships"],
    location: "New York, NY",
    jobTitle: "Managing Director",
    company: "FinanceHub",
  },
  {
    id: "alum-003",
    name: "Emily Watson",
    email: "emily.watson@bio.com",
    graduationYear: 2018,
    major: "Biology",
    lastDonation: 1000,
    totalDonations: 3000,
    engagementScore: 65,
    lastEngagementDate: "2025-08-10",
    interests: ["Research", "Healthcare", "Community"],
    location: "Boston, MA",
    jobTitle: "Research Scientist",
    company: "BioLabs",
  },
  {
    id: "alum-004",
    name: "James Park",
    email: "jpark@creative.com",
    graduationYear: 2016,
    major: "Fine Arts",
    lastDonation: 500,
    totalDonations: 2000,
    engagementScore: 45,
    lastEngagementDate: "2025-07-05",
    interests: ["Arts", "Culture", "Student Programs"],
    location: "Los Angeles, CA",
    jobTitle: "Creative Director",
    company: "DesignStudio",
  },
  {
    id: "alum-005",
    name: "Lisa Thompson",
    email: "lthompson@law.com",
    graduationYear: 2010,
    major: "Law",
    lastDonation: 10000,
    totalDonations: 45000,
    engagementScore: 95,
    lastEngagementDate: "2025-10-10",
    interests: ["Law", "Social Justice", "Scholarships"],
    location: "Washington, DC",
    jobTitle: "Senior Partner",
    company: "LawFirm LLC",
  },
  {
    id: "alum-006",
    name: "David Kim",
    email: "dkim@startup.com",
    graduationYear: 2017,
    major: "Entrepreneurship",
    lastDonation: 3000,
    totalDonations: 6000,
    engagementScore: 72,
    lastEngagementDate: "2025-09-15",
    interests: ["Startups", "Innovation", "Mentorship"],
    location: "Austin, TX",
    jobTitle: "Founder & CEO",
    company: "StartupXYZ",
  },
]

export const mockCampaigns: Campaign[] = [
  {
    id: "camp-001",
    name: "Annual Fund 2025",
    description: "Support our mission to provide quality education and research opportunities",
    targetAlumni: ["alum-001", "alum-002", "alum-005"],
    personalizationStrategy: "High-value donors with tech and business interests",
    status: "active",
    createdAt: "2025-09-01",
    startDate: "2025-10-01",
    endDate: "2025-12-31",
    goal: 500000,
    raised: 285000,
    openRate: 0.68,
    clickRate: 0.42,
    conversionRate: 0.28,
  },
  {
    id: "camp-002",
    name: "Scholarship Initiative",
    description: "Fund scholarships for underprivileged students",
    targetAlumni: ["alum-003", "alum-004", "alum-006"],
    personalizationStrategy: "Mid-level donors interested in education and community",
    status: "active",
    createdAt: "2025-08-15",
    startDate: "2025-09-15",
    endDate: "2025-11-30",
    goal: 250000,
    raised: 145000,
    openRate: 0.55,
    clickRate: 0.35,
    conversionRate: 0.18,
  },
]

export const mockEngagementMetrics: EngagementMetric[] = [
  {
    alumniId: "alum-001",
    campaignId: "camp-001",
    emailOpened: true,
    linkClicked: true,
    donated: true,
    donationAmount: 5000,
    timestamp: "2025-10-15",
  },
  {
    alumniId: "alum-002",
    campaignId: "camp-001",
    emailOpened: true,
    linkClicked: true,
    donated: true,
    donationAmount: 2500,
    timestamp: "2025-10-14",
  },
  {
    alumniId: "alum-003",
    campaignId: "camp-002",
    emailOpened: true,
    linkClicked: false,
    donated: false,
    timestamp: "2025-10-10",
  },
]
